### ISSUE TITLE
Opening a file results in error message

### ISSUE THREAD

**Issue by RefusesNames** [LoricAndre/fzterm.nvim#13] opened 2020-11-04 14:12 UTC
After [this issue](https://github.com/LoricAndre/fzterm.nvim/issues/12) was fixed, I started receiving an error message when opening a file (tried it using `:GFiles`, multiple filetypes):
![image](https://user-images.githubusercontent.com/823148/98121552-bafa2d80-1eaf-11eb-9ffd-02836fba5f06.png)
There have not been any special steps involved other than using `:GFiles` and selecting a file, but it is worth mentioning that vim still works after the error message and the file is opened correctly.

For a reference, [this](https://github.com/RefusesNames/vim_config/tree/fzterm) is the configuration used.

**Comment by LoricAndre** [comment] 2020-11-04 14:23
I can't reproduce this, can you please post your nvim --version and the output of `:ls ` ?

**Comment by RefusesNames** [comment] 2020-11-04 14:37
**Version**: NVIM v0.5.0-773-g932585fd9

**Before opening anything:**
```
:ls
  1 %a   "[No Name]"                    line 1
```
**Steps to reproduce:**
1. Go to the nvim directory of the configuration I posted.
2. `:GFiles` and select `.gitignore` (works with other files, too)
3. Error message shows up

**After opening the file:**
```
:ls
  1 %a   ".gitignore"                   line 1
```

(the problem is not limited to this folder, but everywhere)

**Comment by LoricAndre** [comment] 2020-11-04 14:58
Can you update you neovim and try again please ? The function was only added 26 days ago apparently and you seem to be running an older version than mine

**Comment by RefusesNames** [comment] 2020-11-05 07:46
It does not seem related to versions of neovim or this plugin. Just tried it with
```
NVIM v0.5.0-808-gee3acef38
```
and this fzterm commit:
```
bfcdbdb5f79509461906fffa5fd8ea20019ddfce
```
I can try to build a minimal example later, but for now I only have my full setup [here](https://github.com/RefusesNames/vim_config/tree/fzterm).

**Comment by LoricAndre** [comment] 2020-11-05 11:59
All right, what does calling `:lua vim.api.nvim_buf_delete()` return in vim ?

**Comment by RefusesNames** [comment] 2020-11-05 14:55
`:lua vim.api.nvim_buf_delete()` returns:
```
E5108: Error executing lua [string ":lua"]:1: Expected 2 arguments
```

I just saw that you pushed a new commit and after updating the new error message is:
```
Error detected while processing TermClose Autocommands for "<buffer=2>":
E5108: Error executing lua ...-data\site\pack\packer\start\fzterm\lua\fzterm\utils.lua:24: Invalid buffer id: 2
```
(I had not open buffers, only opened vim, and executed `:GFiles`)

**Comment by LoricAndre** [comment] 2020-11-05 15:52
This should be fixed in https://github.com/LoricAndre/fzterm.nvim/commit/f74b98a3e9664365285ebf4b71da838629d038ba, can you check it out ?

**Closed as completed** 2020-11-07 12:57 UTC
